# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'graphics.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDial, QLCDNumber,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStackedWidget, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(878, 697)
        font = QFont()
        font.setFamilies([u"SWIsot1"])
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color: rgb(4, 4, 4);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(280, 110, 531, 461))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(33, 33, 33);")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.dial = QDial(self.page)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(380, 90, 141, 131))
        self.dial.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 170, 0);\n"
"background-color: rgb(8, 8, 8);")
        self.dial.setMinimum(20)
        self.dial.setMaximum(70)
        self.dial.setValue(21)
        self.lcdNumber = QLCDNumber(self.page)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(60, 120, 221, 81))
        self.lcdNumber.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.pushButton_4 = QPushButton(self.page)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(420, 250, 71, 71))
        self.pushButton_4.setStyleSheet(u"background-color: rgb(0, 85, 0);")
        self.pushButton_5 = QPushButton(self.page)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(420, 340, 71, 71))
        self.pushButton_5.setStyleSheet(u"background-color: rgb(170, 0, 0);")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 40, 141, 16))
        font1 = QFont()
        font1.setPointSize(14)
        self.label_2.setFont(font1)
        self.radioButton = QRadioButton(self.page)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(60, 250, 92, 20))
        self.radioButton_2 = QRadioButton(self.page)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(190, 250, 92, 20))
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 280, 49, 16))
        self.label_4.setStyleSheet(u"background-color: rgb(0, 255, 0);")
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(210, 280, 49, 16))
        self.label_5.setStyleSheet(u"background-color: rgb(0, 255, 0);")
        self.lcdNumber_2 = QLCDNumber(self.page)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(60, 340, 221, 81))
        self.lcdNumber_2.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(60, 90, 91, 16))
        self.label_12 = QLabel(self.page)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 310, 101, 16))
        self.label_13 = QLabel(self.page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 40, 251, 21))
        self.label_14 = QLabel(self.page)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(390, 20, 91, 20))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 30, 181, 16))
        self.label_18.setFont(font1)
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(60, 100, 151, 31))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        self.label_19.setFont(font2)
        self.comboBox = QComboBox(self.page_2)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(60, 140, 131, 24))
        self.pushButton_15 = QPushButton(self.page_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(60, 220, 181, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.pushButton_15.setFont(font3)
        self.pushButton_16 = QPushButton(self.page_2)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(60, 260, 181, 31))
        self.pushButton_16.setFont(font3)
        self.pushButton_17 = QPushButton(self.page_2)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(340, 120, 111, 51))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.pushButton_17.setFont(font4)
        self.LCD_INDICATOR = QLCDNumber(self.page_2)
        self.LCD_INDICATOR.setObjectName(u"LCD_INDICATOR")
        self.LCD_INDICATOR.setGeometry(QRect(350, 220, 111, 31))
        self.LCD_INDICATOR.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.STEP = QLabel(self.page_2)
        self.STEP.setObjectName(u"STEP")
        self.STEP.setGeometry(QRect(350, 280, 101, 31))
        font5 = QFont()
        font5.setBold(True)
        self.STEP.setFont(font5)
        self.DIRECTION_AUTO = QLabel(self.page_2)
        self.DIRECTION_AUTO.setObjectName(u"DIRECTION_AUTO")
        self.DIRECTION_AUTO.setGeometry(QRect(350, 340, 101, 16))
        self.DIRECTION_AUTO.setFont(font5)
        self.label_3 = QLabel(self.page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(350, 260, 49, 16))
        self.label_3.setFont(font5)
        self.label_29 = QLabel(self.page_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(350, 320, 71, 16))
        self.label_29.setFont(font5)
        self.stackedWidget.addWidget(self.page_2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 461, 71))
        font6 = QFont()
        font6.setFamilies([u"Adobe Fan Heiti Std"])
        font6.setPointSize(48)
        font6.setBold(True)
        self.label.setFont(font6)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 170, 151, 51))
        font7 = QFont()
        font7.setFamilies([u"Swis721 LtEx BT"])
        font7.setPointSize(20)
        font7.setBold(False)
        self.pushButton.setFont(font7)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 240, 211, 51))
        font8 = QFont()
        font8.setFamilies([u"Swis721 LtEx BT"])
        font8.setPointSize(20)
        self.pushButton_2.setFont(font8)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(280, 90, 531, 21))
        self.label_20.setStyleSheet(u"background-color: rgb(170, 0, 0);")
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(280, 570, 531, 21))
        self.label_21.setStyleSheet(u"background-color: rgb(170, 0, 0);")
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(810, 90, 20, 501))
        self.label_23.setStyleSheet(u"background-color: rgb(170, 0, 0);")
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 90, 21, 501))
        self.label_22.setStyleSheet(u"background-color: rgb(170, 0, 0);")
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 360, 2071, 791))
        self.label_24.setStyleSheet(u"background-color: rgb(182, 178, 174);")
        self.label_connection = QLabel(self.centralwidget)
        self.label_connection.setObjectName(u"label_connection")
        self.label_connection.setGeometry(QRect(660, 40, 101, 21))
        self.label_connection.setFont(font3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_24.raise_()
        self.stackedWidget.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_22.raise_()
        self.label_connection.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 878, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"MANUAL MODE", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"FORWARD", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"BACKWARD", None))
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"SET FRECUENCY", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"REAL FRECUENCY", None))
        self.label_13.setText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"MOTOR_STATE", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"AUTOMATED MODE", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"load .INI file", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"ADD NEW CONFIGURATION", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"DELETE CONFIGURATION", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"APPLY", None))
        self.STEP.setText("")
        self.DIRECTION_AUTO.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"STEP", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"DIRECTION", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"CommandFlex", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"MANUAL", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"AUTOMATED", None))
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_23.setText("")
        self.label_22.setText("")
        self.label_24.setText("")
        self.label_connection.setText("")
    # retranslateUi

